Added changelog, prepared release
exasol/udf-mock-python pull request #45
Opened 2023-11-21 12:55 UTC by MarleneKress79789

2023-11-21 14:49 UTC, tkilias approved these changes

2023-11-22 07:45 UTC, ckunki requested changes

2023-11-22 07:45 UTC, ckunki commented on .github/pull_request_template.md
> +* [ ] Is the title of the Pull Request correct?
```suggestion
* [ ] Is the title of the pull request correct?
```

2023-11-22 07:45 UTC, ckunki commented on .github/pull_request_template.md
> +* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../../pulls) for the same update/change? <!-- markdown-link-check-disable-line -->
```suggestion
* [ ] Have you checked to ensure there aren't other open [pull requests](../../../../pulls) for the same update/change? <!-- markdown-link-check-disable-line --> 
```

2023-11-22 07:45 UTC, ckunki commented on .github/pull_request_template.md
> +* [ ] Are you mentioning the issue which this PullRequest fixes ("Fixes...")
```suggestion
* [ ] Are you mentioning the issue which this pull request fixes ("Fixes...")
```

2023-11-22 07:45 UTC, ckunki commented on README.md
> +udf-mock-python = = "^0.1.0"
```suggestion
udf-mock-python = "^0.1.0"
```

2023-11-22 07:45 UTC, ckunki commented on doc/changes/changes_0.1.0.md
> +## Summary
```suggestion
## Summary

```

2023-11-22 07:45 UTC, ckunki commented on doc/changes/changes_0.1.0.md
> +This is the initial release of the UDF Mock Python which provides a mock runner for Python3 UDFs which allows you to
```suggestion
This is the initial release of the UDF Mock Python providing a mock runner for Python3 UDFs which allows you to
```

2023-11-22 10:25 UTC, MarleneKress79789 commented on doc/changes/changes_0.1.0.md
> +This is the initial release of the UDF Mock Python which provides a mock runner for Python3 UDFs which allows you to
i like the other more in this case.

2023-11-22 10:25 UTC, MarleneKress79789 commented on doc/changes/changes_0.1.0.md
> +# UDF Mock Python 0.1.0, released 2023.11.21
```suggestion
# UDF Mock Python 0.1.0, released 2023.11.22
```

2023-11-22 10:27 UTC, tkilias approved these changes

2023-11-22 10:33 UTC, merged